# Generated by Django 3.0 on 2020-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200226_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='DepartmentID',
            field=models.IntegerField(),
        ),
    ]
