# Generated by Django 3.0 on 2020-02-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20200226_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='DepartmentID',
        ),
    ]
