# Generated by Django 3.0 on 2020-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_department_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DepartmentID',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
