# Generated by Django 3.0 on 2020-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_department_departmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='DepartmentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
