# Generated by Django 3.0 on 2020-02-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_auto_20200227_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Department', models.CharField(max_length=20)),
                ('EmployeeName', models.CharField(max_length=10)),
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('MailID', models.CharField(max_length=20)),
                ('DOJ', models.CharField(max_length=10)),
            ],
        ),
    ]
