# Generated by Django 3.0 on 2020-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(),
        ),
    ]
