# Generated by Django 3.0 on 2020-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_auto_20200301_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.CharField(max_length=100),
        ),
    ]
